//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scylla.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scylla.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your passwords do not match. ähnelt.
        /// </summary>
        internal static string accCreationPwNoMatch {
            get {
                return ResourceManager.GetString("accCreationPwNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your account has been successfully created! ähnelt.
        /// </summary>
        internal static string accCreationSuccess {
            get {
                return ResourceManager.GetString("accCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account Details ähnelt.
        /// </summary>
        internal static string accountDetails {
            get {
                return ResourceManager.GetString("accountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account editor ähnelt.
        /// </summary>
        internal static string accountEditor {
            get {
                return ResourceManager.GetString("accountEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_bookmark {
            get {
                object obj = ResourceManager.GetObject("add_bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auric Cells ähnelt.
        /// </summary>
        internal static string auricCells {
            get {
                return ResourceManager.GetString("auricCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to login ähnelt.
        /// </summary>
        internal static string backToLogin {
            get {
                return ResourceManager.GetString("backToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bloodpoints {
            get {
                object obj = ResourceManager.GetObject("bloodpoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bloodpoints ähnelt.
        /// </summary>
        internal static string bloodpoints1 {
            get {
                return ResourceManager.GetString("bloodpoints1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bloodweb level ähnelt.
        /// </summary>
        internal static string bloodwebLevel {
            get {
                return ResourceManager.GetString("bloodwebLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break Sets ähnelt.
        /// </summary>
        internal static string breakSets {
            get {
                return ResourceManager.GetString("breakSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap categorize {
            get {
                object obj = ResourceManager.GetObject("categorize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cells {
            get {
                object obj = ResourceManager.GetObject("cells", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Completor ähnelt.
        /// </summary>
        internal static string challengeCompletor {
            get {
                return ResourceManager.GetString("challengeCompletor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change password ähnelt.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changes ähnelt.
        /// </summary>
        internal static string changes {
            get {
                return ResourceManager.GetString("changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configuration has been successfully created! ähnelt.
        /// </summary>
        internal static string configCreated {
            get {
                return ResourceManager.GetString("configCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Config ähnelt.
        /// </summary>
        internal static string configDelete {
            get {
                return ResourceManager.GetString("configDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configuration has been successfully deleted! ähnelt.
        /// </summary>
        internal static string configDeleted {
            get {
                return ResourceManager.GetString("configDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Config ähnelt.
        /// </summary>
        internal static string configExport {
            get {
                return ResourceManager.GetString("configExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configuration has been successfully exported! ähnelt.
        /// </summary>
        internal static string configExported {
            get {
                return ResourceManager.GetString("configExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Config ähnelt.
        /// </summary>
        internal static string configImport {
            get {
                return ResourceManager.GetString("configImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configuration has been successfully imported! ähnelt.
        /// </summary>
        internal static string configImported {
            get {
                return ResourceManager.GetString("configImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid config file! ähnelt.
        /// </summary>
        internal static string configInvalid {
            get {
                return ResourceManager.GetString("configInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Config ähnelt.
        /// </summary>
        internal static string configLoad {
            get {
                return ResourceManager.GetString("configLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configuration has been successfully loaded! ähnelt.
        /// </summary>
        internal static string configLoaded {
            get {
                return ResourceManager.GetString("configLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Config Name ähnelt.
        /// </summary>
        internal static string configName {
            get {
                return ResourceManager.GetString("configName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please fill in the name of the configuration. ähnelt.
        /// </summary>
        internal static string configNoName {
            get {
                return ResourceManager.GetString("configNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the name of the configuration... ähnelt.
        /// </summary>
        internal static string configNoSelect {
            get {
                return ResourceManager.GetString("configNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configs ähnelt.
        /// </summary>
        internal static string configs {
            get {
                return ResourceManager.GetString("configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Config ähnelt.
        /// </summary>
        internal static string configSave {
            get {
                return ResourceManager.GetString("configSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Config ähnelt.
        /// </summary>
        internal static string configSelect {
            get {
                return ResourceManager.GetString("configSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm password ähnelt.
        /// </summary>
        internal static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creation date ähnelt.
        /// </summary>
        internal static string creationDate {
            get {
                return ResourceManager.GetString("creationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap currency {
            get {
                object obj = ResourceManager.GetObject("currency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currency ähnelt.
        /// </summary>
        internal static string currency1 {
            get {
                return ResourceManager.GetString("currency1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DBD version ähnelt.
        /// </summary>
        internal static string dbdVersion {
            get {
                return ResourceManager.GetString("dbdVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default Settings (Linked Progress) ähnelt.
        /// </summary>
        internal static string defaultSettingsLinked {
            get {
                return ResourceManager.GetString("defaultSettingsLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detail informations ähnelt.
        /// </summary>
        internal static string detailInformations {
            get {
                return ResourceManager.GetString("detailInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Devotion ähnelt.
        /// </summary>
        internal static string devotion {
            get {
                return ResourceManager.GetString("devotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editor {
            get {
                object obj = ResourceManager.GetObject("editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scylla was unable to find the required files to run. Please reinstall Scylla. ähnelt.
        /// </summary>
        internal static string encNotFound {
            get {
                return ResourceManager.GetString("encNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EpicGames {
            get {
                object obj = ResourceManager.GetObject("EpicGames", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expiry ähnelt.
        /// </summary>
        internal static string expiry {
            get {
                return ResourceManager.GetString("expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_circle {
            get {
                object obj = ResourceManager.GetObject("help_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_circle_white {
            get {
                object obj = ResourceManager.GetObject("help_circle_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string home1 {
            get {
                return ResourceManager.GetString("home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore Killswitch ähnelt.
        /// </summary>
        internal static string ignoreKillswitch {
            get {
                return ResourceManager.GetString("ignoreKillswitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Item amount ähnelt.
        /// </summary>
        internal static string itemAmount {
            get {
                return ResourceManager.GetString("itemAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killer Country ähnelt.
        /// </summary>
        internal static string killerCountry {
            get {
                return ResourceManager.GetString("killerCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killer Name ähnelt.
        /// </summary>
        internal static string killerName {
            get {
                return ResourceManager.GetString("killerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killer isn&apos;t from Steam Platform. ähnelt.
        /// </summary>
        internal static string killerNotFromSteam {
            get {
                return ResourceManager.GetString("killerNotFromSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killer Rank ähnelt.
        /// </summary>
        internal static string killerRank {
            get {
                return ResourceManager.GetString("killerRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killer Rating ähnelt.
        /// </summary>
        internal static string killerRating {
            get {
                return ResourceManager.GetString("killerRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killer reveal ähnelt.
        /// </summary>
        internal static string killerReveal {
            get {
                return ResourceManager.GetString("killerReveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last login ähnelt.
        /// </summary>
        internal static string lastLogin {
            get {
                return ResourceManager.GetString("lastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap level {
            get {
                object obj = ResourceManager.GetObject("level", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level ähnelt.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        internal static string licence {
            get {
                return ResourceManager.GetString("licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap license {
            get {
                object obj = ResourceManager.GetObject("license", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Settings is an essential feature that allows you to customize various aspects of your gameplay experience across all your characters in the game. This setting provides you with the flexibility to adjust the prestige level, amount of items, and the blood web level, among other things. Toggle ON to link all. ähnelt.
        /// </summary>
        internal static string linkedProgressTooltip {
            get {
                return ResourceManager.GetString("linkedProgressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scylla was unable to load. Please reinstall Scylla. ähnelt.
        /// </summary>
        internal static string loadError {
            get {
                return ResourceManager.GetString("loadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lobby informations ähnelt.
        /// </summary>
        internal static string lobbyInformations {
            get {
                return ResourceManager.GetString("lobbyInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login to old Cosmetics Unlocker ähnelt.
        /// </summary>
        internal static string loginToOldCosmetics {
            get {
                return ResourceManager.GetString("loginToOldCosmetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mail {
            get {
                object obj = ResourceManager.GetObject("mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match ID ähnelt.
        /// </summary>
        internal static string matchID {
            get {
                return ResourceManager.GetString("matchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MicrosoftStore {
            get {
                object obj = ResourceManager.GetObject("MicrosoftStore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc ähnelt.
        /// </summary>
        internal static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miscellaneous features ähnelt.
        /// </summary>
        internal static string miscFeatures {
            get {
                return ResourceManager.GetString("miscFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Months ähnelt.
        /// </summary>
        internal static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap murder {
            get {
                object obj = ResourceManager.GetObject("murder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die News ähnelt.
        /// </summary>
        internal static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overlay ähnelt.
        /// </summary>
        internal static string overlay {
            get {
                return ResourceManager.GetString("overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap password {
            get {
                object obj = ResourceManager.GetObject("password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string password1 {
            get {
                return ResourceManager.GetString("password1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Platform ähnelt.
        /// </summary>
        internal static string platform {
            get {
                return ResourceManager.GetString("platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position ähnelt.
        /// </summary>
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap premium {
            get {
                object obj = ResourceManager.GetObject("premium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prestige level ähnelt.
        /// </summary>
        internal static string prestigeLevel {
            get {
                return ResourceManager.GetString("prestigeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap profile {
            get {
                object obj = ResourceManager.GetObject("profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will randomize the amount of every item, addon and offering. The &quot;Default Settings&quot; switch needs to be active for this to work. ähnelt.
        /// </summary>
        internal static string randomizerTooltip {
            get {
                return ResourceManager.GetString("randomizerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rank Reveal ähnelt.
        /// </summary>
        internal static string rankReveal {
            get {
                return ResourceManager.GetString("rankReveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Region changer ähnelt.
        /// </summary>
        internal static string regionChanger {
            get {
                return ResourceManager.GetString("regionChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember me ähnelt.
        /// </summary>
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset HWID ähnelt.
        /// </summary>
        internal static string resetHWID {
            get {
                return ResourceManager.GetString("resetHWID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon scylla {
            get {
                object obj = ResourceManager.GetObject("scylla", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scylla is outdated. Please wait while Scylla updates itself. ähnelt.
        /// </summary>
        internal static string scyllaOutdated {
            get {
                return ResourceManager.GetString("scyllaOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scylla - Register ähnelt.
        /// </summary>
        internal static string scyllaRegister {
            get {
                return ResourceManager.GetString("scyllaRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scylla has been updated. Please wait while Scylla restarts itself. ähnelt.
        /// </summary>
        internal static string scyllaUpdated {
            get {
                return ResourceManager.GetString("scyllaUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Platform ähnelt.
        /// </summary>
        internal static string selectPlatform {
            get {
                return ResourceManager.GetString("selectPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shards {
            get {
                object obj = ResourceManager.GetObject("shards", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shards ähnelt.
        /// </summary>
        internal static string shards1 {
            get {
                return ResourceManager.GetString("shards1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spoof Currency ähnelt.
        /// </summary>
        internal static string spoofCurrency {
            get {
                return ResourceManager.GetString("spoofCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spoofed successfully! ähnelt.
        /// </summary>
        internal static string spoofedSuccessfully {
            get {
                return ResourceManager.GetString("spoofedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spoof Level ähnelt.
        /// </summary>
        internal static string spoofLevel {
            get {
                return ResourceManager.GetString("spoofLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Started, launch game please. ähnelt.
        /// </summary>
        internal static string startedLaunchGamePlease {
            get {
                return ResourceManager.GetString("startedLaunchGamePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Loader ähnelt.
        /// </summary>
        internal static string startLoader {
            get {
                return ResourceManager.GetString("startLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steam ID ähnelt.
        /// </summary>
        internal static string steamID {
            get {
                return ResourceManager.GetString("steamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steam profile ähnelt.
        /// </summary>
        internal static string steamProfile {
            get {
                return ResourceManager.GetString("steamProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscription ähnelt.
        /// </summary>
        internal static string subscription {
            get {
                return ResourceManager.GetString("subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support ticket ähnelt.
        /// </summary>
        internal static string supportTicket {
            get {
                return ResourceManager.GetString("supportTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scylla minimized to the systray. Click the Icon, to open it again. ähnelt.
        /// </summary>
        internal static string systrayText {
            get {
                return ResourceManager.GetString("systrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ultra {
            get {
                object obj = ResourceManager.GetObject("ultra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unlocker {
            get {
                object obj = ResourceManager.GetObject("unlocker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updated ähnelt.
        /// </summary>
        internal static string updated {
            get {
                return ResourceManager.GetString("updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        internal static string user1 {
            get {
                return ResourceManager.GetString("user1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visual Currency Spoof ähnelt.
        /// </summary>
        internal static string visualCurrencySpoof {
            get {
                return ResourceManager.GetString("visualCurrencySpoof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting time ähnelt.
        /// </summary>
        internal static string waitingTime {
            get {
                return ResourceManager.GetString("waitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Years ähnelt.
        /// </summary>
        internal static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
